#INCLUDE 'Protheus.ch'


 /*/{Protheus.doc} DECLVAR
    (eXERCÍCIO DO CURSO)
    @type  User Function
    @author Rogério Sacramento
    @since 24/01/2023
    @version 1
   
    /*/
User Function DECLVAR()

Local nAlunos := 0
Local aNotas  := {}
Local nMedia  := 0
Local cNome   := "Rogerio"
Local cMsgApr := "Aprovado"
Local cMsgRep := "Reprovado"
Local lApro   := .F.
Local Data    := CTOD("24/01/2023")
Local bBloco  := {||}

Return 
