#INCLUDE 'TOTVS.CH'

//FUNÇÃO UTILIZADA PARA TESTE DO LOGSERVER

User Function MyLogSe()

Alert("TESTE ALERT LogSERVER")  
Conout("TESTE CONOUT LogSERVER")
FWLOGMSG('WARN',,'SIGAFAT',FUNNAME(),'','01',"TESTE LOG SERVER 2" ,0,0,{})  

Return 
